splunk:
    conf:
        indexes:
            directory: /opt/splunk/etc/apps/search/local
            content:
                metrics:
                    coldPath: $SPLUNK_DB/metrics/colddb
                    datatype: metric
                    homePath: $SPLUNK_DB/metrics/db
                    maxTotalDataSizeMB: 512000
                    thawedPath: $SPLUNK_DB/metrics/thaweddb
                ethereum:
                    coldPath: $SPLUNK_DB/ethereum/colddb
                    homePath: $SPLUNK_DB/ethereum/db
                    maxTotalDataSizeMB: 512000
                    thawedPath: $SPLUNK_DB/ethereum/thaweddb
