version: '3.6'

services:
    splunk:
        image: splunk/splunk:latest
        container_name: splunk
        environment:
            - SPLUNK_START_ARGS=--accept-license
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_PASSWORD=changeme
        ports:
            - 8000:8000
            - 8088:8088
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000']
            interval: 5s
            timeout: 5s
            retries: 20
        volumes:
            - ./splunk.yml:/tmp/defaults/default.yml
    ethlogger:
        image: docker.pkg.github.com/splunk/splunk-connect-for-ethereum/ethlogger:latest
        container_name: ethlogger
        environment:
            - ETH_RPC_URL=https://dai.poa.network
            - NETWORK_NAME=xdai
            # Use these environment variables to connect to infura
            # - ETH_RPC_URL=https://mainnet.infura.io/v3/<your infura project id>
            # - NETWORK_NAME=mainnet
            - START_AT_BLOCK=latest
            - SPLUNK_HEC_URL=https://splunk:8088
            - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
            - SPLUNK_EVENTS_INDEX=main
            - SPLUNK_METRICS_INDEX=metrics
            - SPLUNK_INTERNAL_INDEX=metrics
            - SPLUNK_HEC_REJECT_INVALID_CERTS=false
        depends_on:
            - splunk
