name: CI

on: [push]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: build
              run: |
                  npm i -g yarn
                  yarn install
                  yarn build
    test:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: test
              run: |
                  npm i -g yarn
                  yarn install
                  yarn lint
                  yarn test --verbose
              env:
                  CI: true
