name: CI

on: [push]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Build ethlogger CLI
              run: |
                  npm i -g yarn
                  yarn install --frozen-lockfile
                  yarn build
    docker-image:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v1
            - name: Build docker image
              run: docker build -t ethlogger .
            - name: Login to docker registry
              run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - name: Publish docker image
              run: |
                  docker tag ethlogger docker.pkg.github.com/$GITHUB_REPOSITORY/ethlogger:$GITHUB_SHA
                  docker push docker.pkg.github.com/$GITHUB_REPOSITORY/ethlogger:$GITHUB_SHA
    unit-tests:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Run unit tests and linter
              run: |
                  npm i -g yarn
                  yarn install --frozen-lockfile
                  yarn test --verbose
              env:
                  CI: true
    check-format:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Check code format
              run: |
                  npm i -g yarn
                  yarn install --frozen-lockfile
                  yarn format:verify
              env:
                  CI: true
    check-generated-files:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Check if generated files are up-to-date
              run: |
                  npm i -g yarn
                  yarn install --frozen-lockfile
                  yarn generate:all
                  echo "Checking if generated files are up-to-date"
                  git diff --exit-code
              env:
                  CI: true
