name: Post-release

on:
    push:
        tags: [v*]

jobs:
    post-release:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Semantic release
              run: |
                  npm i -g yarn
                  yarn install --frozen-lockfile
                  yarn ts-node scripts/postrelease.ts $GITHUB_REF
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
